# Tekton task to perform vulnerability scan via trivy
# Author: Giuseppe Magnotta <giuseppe.magnotta@gmail.com>
# Version 0.1
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: vulnerability-scan
spec:
  description: Perform vulnerability scan via trivy
  params:
    - name: IMAGE
      default: 'quay.io/gmagnotta/trivy-with-dbs:20230102'
      type: string
    - name: IMAGETOSCAN
      type: string
    - name: SEVERITIES
      default: 'CRITICAL'
      type: string
    - name: ENABLED
      type: string
      default: 'true'
  workspaces:
    - name: source
  steps:
    - name: vulnerability-scan
      image: $(params.IMAGE)
      resources: {}
      args: ["--cache-dir", "/cache/trivy", "image", "--skip-db-update", "--skip-java-db-update", "--offline-scan", "--exit-code", "1", "--severity", "$(params.SEVERITIES)", "$(params.IMAGETOSCAN)"]
