apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: vulnerability-sbom
spec:
  description: Perform vulnerability scan via grype on sbom file
  params:
    - name: IMAGE
      default: 'quay.io/gmagnotta/grype-with-db:20230103'
      type: string
    - name: SBOM
      default: 'result.cdx'
      type: string
  workspaces:
    - name: source
  steps:
    - name: vulnerability-scan
      image: $(params.IMAGE)
      resources: {}
      args: ["$(params.SBOM)"]
