---
- name: Initialize an OCP Cluster with Project and essentials secrets
  hosts: localhost
  vars:
    project: "myproject"
    registry_username: "myuser"
    registry_password: "mypassword"
  tasks:
    - name: Create Project
      kubernetes.core.k8s:
        name: "{{ project }}"
        api_version: project.openshift.io/v1
        kind: Project
        state: present
    - name: Create secret
      command: "oc create secret docker-registry redhatregistryio --docker-server=registry.redhat.io --docker-username={{ registry_username }} --docker-password={{ registry_password }} -n {{ project }}" 
    - name: Link secret to default
      command: "oc secrets link default redhatregistryio --for=pull -n {{ project }}"
    - name: Link secret to builder
      command: "oc secrets link builder redhatregistryio -n {{ project }}"

    - name: Create OperatorGroup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: "{{ project }}"
            namespace: "{{ project }}"
          spec:
            targetNamespaces:
              - "{{ project }}"
            upgradeStrategy: Default
